### ISSUE TITLE
Lazy Pack Generator 1.2.1 compatibility

### ISSUE THREAD

**Issue by Epihanor** [hoverbike1/TOTK-Mods-collection#155]
Although many mods already have 1.2.1 compatibility, Lazy Pack Generator is stuck at 1.2.0.

Please, make the lazy ones (like myself) up-to-date again :D

**Comment by hoverbike1** [comment]
without chuck's dynamicfps, i can't

**Comment by Snipy44** [comment]
Nothing for 1.2.1 ? pls :/

**Comment by hoverbike1** [comment]
New method developed by @MaxLastBreath
Check out the new TOTK Optimiser, and the Ultracam method it has for 1.2.1
It seems we are back on track.
