### ISSUE TITLE
1.2.1 Support

### ISSUE THREAD

**Issue by Mario-119** [hoverbike1/TOTK-Mods-collection#156]
Official support for 1.2.1 would be very nice if that's feasible

**Comment by hoverbike1** [comment]
all i can do is to check chuck's dynamicfps for updates, and he's gone silent since about a month ago

**Comment by Mario-119** [comment]
Understandable, hope he's alright

**Comment by sekelus** [comment]
> Understandable, hope he's alright

i hope so too !!

**Comment by tigert1998** [comment]
Are there any updates?

**Comment by tigert1998** [comment]
When I first opened the issue, I just started playing TOTK. When it is closed, I have finished playing TOTK for several weeks. LOL
