### ISSUE TITLE
Increased Camera Speed has been updated to 1.2.1 but don't seems to work

### ISSUE THREAD

**Issue by BrutolocoW** [hoverbike1/TOTK-Mods-collection#162]
Even though the mod is supposedly updated to version 1.2.1 it doesn't seem to work, the camera moves at normal speed. 
While in version 1.2.0 it moves fast. 

Has anyone else tried it?

I think this mod is quite useful, it is very noticeable when you are used to it, because the camera moves very slowly.

**Comment by crunkl3r** [comment]
same

**Comment by debrl** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by crunkl3r** [comment]
StevensND,
Yes, that worked, thank you.

**Comment by hoverbike1** [comment]
> I did a bad update with this mod so that's why it's not working. **However the owner of this TOTK-Mods-Collection has not spoken to me since August 26th** (even though I have sent him [updated stuff](https://i.imgur.com/LVLBViC.png) to add) so that's why it's not fixed. Try this instead and let me know if it's working now:
> 
> ```
> @nsobid-9B4E43650501A4D4489B4BBFDB740F26AF3CF850
> 
> @flag print_values
> @flag offset_shift 0x100
> 
> // Camera Speed Fix for v1.2.1
> // Increases the camera speed, can be adjusted in the settings. 
> 
> @enabled
> 03811C2C 0000A03F
> 00D180F8 0990211E
> @stop
> ```

hey man, good to see you're still active

i've been busy with my new workplace, so ive been distracted, also, i wasn't able to find this stuff in our chat, so ive went ahead and copied it from here.

though i did parse the new cheats from bad1dea _eventually_

/h
