### ISSUE TITLE
60 fps mod not working v1.2.1

### ISSUE THREAD

**Issue by L0WR1D3Rz** [hoverbike1/TOTK-Mods-collection#164]
Hi, i hope someone can give a helping hand. I've installed totk with 1.2.1 update in yuzu. I've installed mods dynamic 60fps, dynamic fps 1.5.5 main and dynamic fps 1.5.5 1080p res...wiped caches and storage and restarted system... Still when I launch the game it is visibly capped at 30fps as if none if the mods work. My screen refresh rate is 60hz so there is no reason why it would cap at 30. Tried also the 45fps mod but that didn't work either. 
![IMG_20231217_090449](https://github.com/hoverbike1/TOTK-Mods-collection/assets/106449726/ad82e35e-fc33-4002-be95-2cd50b61c9c0)
Am I doing anything wrong?  Attached the picture if the mods activated

**Comment by L0WR1D3Rz** [comment]
Update:disabling update 1.2.1 makes the mods work... Are they incompatible with 1.2.1?

**Comment by L0WR1D3Rz** [comment]
Update : it looks like when i disable update 1.2.1 they work. How can i make them work with the latest update?

**Comment by L0WR1D3Rz** [comment]
I just realized they aren't updated to 1.2.1...pity. Ignore this ticket and apologies.

**Comment by MaxLastBreath** [comment]
Use Ultracam, it has 60 fps built in
