### ISSUE TITLE
Infinite Rupees (1.0.0 to 1.2.0)

### ISSUE THREAD

**Issue by User8631** [hoverbike1/TOTK-Mods-collection#167]
Does not work. I don't see any Rupees it says 0. When I go to the buyer item it does not show that i can't buy it

**Comment by debrl** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by User8631** [comment]
Nevermind it works!
Can u add a mod that has infinite rupees but like really Infinite like 1000,00000 rupees
