### ISSUE TITLE
Ladder climbing issue in Sinakawak Shrine

### ISSUE THREAD

**Issue by brentward** [hoverbike1/TOTK-Mods-collection#174]
I'm at 120 fps and climbing speed is very slow in the ladder at the end of Sinakawak Shrine and when I get to the top I fall back down and can't climb out.. I have FPS set to 120, resolution set to 4k and shadow resolution set to 1024x. Let me know what other info you need.

**Comment by MaxLastBreath** [comment]
will be fixed in the future

**Comment by hoverbike1** [comment]
Issue has been resolved.
