### ISSUE TITLE
Optimizer not doing anything on Apply/Launch/Extract

### ISSUE THREAD

**Issue by markosopcic** [hoverbike1/TOTK-Mods-collection#176]
Hi! I wanted to try out the optimizer to setup my yuzu config, but whenever i click apply/launch/extract, nothing happens. The log doesn't show anything at all, and the yuzu config doesn't update - no mods are added. I'm attaching a video of my process. 
I'm on Arch with i3 as VM, not sure if that matters. I'm not sure if I'm doing something wrong, but I'd expect *something* to happen after pressing apply - at least an error log in the console.

Any help is appreciated, thank you.

https://github.com/hoverbike1/TOTK-Mods-collection/assets/32719316/2eca88ec-acd0-45e2-9b56-bcbe676f9ff2

**Comment by debrl** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hoverbike1** [comment]
We believe this issue to be related to the OS, or the hardware config. We cannot replicate the issue.
