### ISSUE TITLE
60fps not working on v1.1.1

### ISSUE THREAD

**Issue by Fxzzi** [hoverbike1/TOTK-Mods-collection#178]
It seems I'm unable to get 60fps working with v1.1.1. The mods provided in the 1.1.1 version of the mod collection don't seem to work for that version. Any alternatives or versions with same fps and dupe glitches?

**Comment by MaxLastBreath** [comment]
TOTK Optimizer does work with 1.1.1 version

**Comment by Fxzzi** [comment]
> TOTK Optimizer does work with 1.1.1 version

No problem. I was able to get ultracam working on 1.1.1 so I assumed totk optimizer would work too. It also has a zip file for version 1.1.1.
