### ISSUE TITLE
GPU RX 6650 XT not detected 

### ISSUE THREAD

**Issue by Moksys1** [hoverbike1/TOTK-Mods-collection#179]
I opened the totk optimizer and the program doesn't detect my gpu, only detect my cpu AMD ryzen 5 5600G and my 16 GB RAM, please help
![Imagen de WhatsApp 2024-06-21 a las 12 21 33_f626ea44](https://github.com/hoverbike1/TOTK-Mods-collection/assets/97849157/2d9f6756-6968-47dd-8394-b63176736cf9)

**Comment by hoverbike1** [comment]
Give the new version a try, let us know if your issues still persists.
