### ISSUE TITLE
macOS Support?

### ISSUE THREAD

**Issue by MysticalOS** [hoverbike1/TOTK-Mods-collection#180]
I kind of preferred this repo when it was just mods repo cause the new optimizer apps don't leave any solution to mac users anymore (and switch emulation is pretty bit on mac since we have excellent switch emulation thanks to hypervisor (which remaps switch arm to apple arm).

**Comment by hoverbike1** [comment]
I believe that you can run the software through Wine. You could potentially also dualboot Windows. Or run a VM.

Without actual hardware to develop on, its not possible for us to port to Apple Silicon, though if we had such hardware, we would be happy to expand to those platforms.

**Comment by hoverbike1** [comment]
Experimental MacOS port courtesy of @alvindimas05
