### ISSUE TITLE
Moonwalking after 15-20 mins of play

### ISSUE THREAD

**Issue by Rellawing** [hoverbike1/TOTK-Mods-collection#181]
After 15-20 mins of playtime, I'm moonwalking as the FPS grinds down gradually. At first I'll play at 40-45fps, then it throttles down to 30fps, and from there it goes to 20fps and goes as low as 10fps if I let it going on. It's not just an fps issue either. I start literally moving in slow motion, like I'm moonwalking and the game becomes unplayable, and that's whether I'm using TotK Optimizer or not.

I use Early Yuzu 4176 and right now, aside from some cheats like stamina, arrows, unbreakable weapons, I'm running no mods. I've tried other builds of Yuzu with little improvement and Ryujinx plays TotK so unstably it randomly crashes, while the slowdown issue does not occur in that emulator, it also chugs horribly, making the experience unpleasant in another way.

**Comment by hoverbike1** [comment]
I mean, I hate to say it, but it sounds like your PC, specifically your CPU, is thermal throttling. If it doesnt matter what Yuzu version, and it doesnt matter if you're using the optimizer or not, and there is no improvement in Ryujinx, the only things that haven't been touched on is the game dump, and the actual PC hardware.

Try monitoring the CPU's stats after 30 minutes of heavy load (e.g. emulating totk) and see if anything sticks out. Low power consumption, high thermals, maybe its in the wrong PL state, maybe its just intel turbo boost or amd precision boost overclock that is having extremely short durations, which can be extended, assuming that thermals aren't an issue.

**Comment by hoverbike1** [comment]
And alternatively, try using a new, different dump of TOTK, and make sure to install some update. 1.0.0 has quite a few issues.
