### ISSUE TITLE
Not 60 FPS on recommended setup

### ISSUE THREAD

**Issue by nickash2** [hoverbike1/TOTK-Mods-collection#182]
I am using yuzu early access 4176.
My specs are:
Processor: AMD Ryzen 9 5900HS with Radeon Graphics, 3301 Mhz, 8 Core(s), 
GPU: NVIDIA RTX 3060 Laptop GPU
RAM: 16 GB

I'm trying to just use the Medium settings and get a solid 30 fps but nothing more than that even if I set the optimizer to 60 fps.

**Comment by hoverbike1** [comment]
You should be able to go above 30 in shrines. If you cannot, you have some other software imposing a 30 fps limit on your game.
