### ISSUE TITLE
[MacOS] Crash at startup on Ryujinx

### ISSUE THREAD

**Issue by Foul-Tarnished** [hoverbike1/TOTK-Mods-collection#183]
Hi

Ryujinx crash at startup when using Ultracam

I set it to 1080p, 1024x shadows, and ticked every settings on the right
I tried JIT and hypervisor, no difference
game version is 1.2.0 and work fine without this mod.

[Ryujinx_1.1.1376_2024-08-18_19-37-10.log](https://github.com/user-attachments/files/16650589/Ryujinx_1.1.1376_2024-08-18_19-37-10.log)
`00:00:20.872 |E| .NET TP Worker [mvk-info] Created 3 swapchain images with initial size (3456, 1962) and contents scale 2.0 for screen Built-in Retina Display.`

This is a Macbook Pro M3 (3456x2234p 16:10 display) running Sonoma 14.5

**Comment by debrl** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hoverbike1** [comment]
Please contact @alvindimas05 on his TOTK-mods repository regarding MacOS issues

**Comment by alvindimas05** [comment]
> Hi
> 
> Ryujinx crash at startup when using Ultracam
> 
> I set it to 1080p, 1024x shadows, and ticked every settings on the right I tried JIT and hypervisor, no difference game version is 1.2.0 and work fine without this mod.
> 
> [Ryujinx_1.1.1376_2024-08-18_19-37-10.log](https://github.com/user-attachments/files/16650589/Ryujinx_1.1.1376_2024-08-18_19-37-10.log) `00:00:20.872 |E| .NET TP Worker [mvk-info] Created 3 swapchain images with initial size (3456, 1962) and contents scale 2.0 for screen Built-in Retina Display.`
> 
> This is a Macbook Pro M3 (3456x2234p 16:10 display) running Sonoma 14.5
Mention me on the discord and I'll help you with it.

**Comment by hoverbike1** [comment]
Unfortunately, without apple equipment to test on, we can do very little with this information. Please seek the developer I linked to above, as he produced the macOS version, and will be able to take a look at this issue.

Alternatively, I'd suggest you post this issue on the discord, assuming you haven't already. They should at least be able to provide you some basic support steps.
