### ISSUE TITLE
Manual Install

### ISSUE THREAD

**Issue by KeinNiemand** [hoverbike1/TOTK-Mods-collection#185]
I don't want to run some exe just to install some mods, it's something that can easily be done manually and it's safer to do manually and gives me more control. Please provide some way to manually download and install the mods.

**Comment by klownk** [comment]
This.

**Comment by debrl** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hoverbike1** [comment]
you've always been able to edit the maxlastbreath.ini file, this is a non-issue, closing

**Comment by klownk** [comment]
"you've always been able to edit the maxlastbreath.ini file, this is a non-issue, closing"
What the hell? Do you know what you are doing? Do you understand english?

**Comment by hoverbike1** [comment]
https://gamebanana.com/mods/480138
![image](https://github.com/user-attachments/assets/9b08b190-c889-42e3-9d15-022c02bc9618)
