### ISSUE TITLE
 Video memory leak

### ISSUE THREAD

**Issue by GodlikeYang** [hoverbike1/TOTK-Mods-collection#186]
During the game, the video memory usage is getting higher and higher. Finally, the video memory is full and the game becomes laggy.

**Comment by GodlikeYang** [comment]
The problem with TOTK Optimizer seems to have existed a few versions ago, the game resolution is 6K

**Comment by Dark-talon** [comment]
this has nothing to do with totk optimizer. its a yuzu memory leak.

**Comment by amayra** [comment]
try different emulators and report back 

is this problem happened even without this mods ?
