### ISSUE TITLE
Steam Controller UI

### ISSUE THREAD

**Issue by Krutonium** [hoverbike1/TOTK-Mods-collection#67]
Basically, does anyone know of/know who might/how to make a UI mod for the Steam Controller?

**Comment by HolographicWings** [comment]
i know how to edit the HUD of the game, i could show you on discord, but there isn's already a mod to do that on game banana ?

**Comment by Krutonium** [comment]
https://gamebanana.com/concepts/2966

As close as I can find, just the art.

**Comment by HolographicWings** [comment]
> https://gamebanana.com/concepts/2966
> 
> As close as I can find, just the art.

DM me on discord, i'll show you how to edit the HUD asset.

**Comment by MADOK1** [comment]
If you mean the Steam Controller as in this:
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/99259670/c4e66a61-1e0b-4c40-b2ea-cfdffbeb2847)
]
Then I'm not sure that there's a mod for it, but if you mean the Steam Controller as in the Steam Deck, that's included in the 16:10 mod:
https://gamebanana.com/mods/download/443462#FileInfo_996800

**Comment by hoverbike1** [comment]
https://gamebanana.com/mods/448437
test this out, let us know if you like it

**Comment by LordBoos** [comment]
@hoverbike1 that one is working perfectly for 1.1.2 and 1.2.0. All buttons are correctly displayed.
Would be nice to have it in the mod pack and not having to download it separately.
